/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'clause-families': ClauseFamily;
    'sub-clauses': SubClause;
    'playbook-entries': PlaybookEntry;
    'counterparty-drafts': CounterpartyDraft;
    'negotiation-log-entries': NegotiationLogEntry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'clause-families': ClauseFamiliesSelect<false> | ClauseFamiliesSelect<true>;
    'sub-clauses': SubClausesSelect<false> | SubClausesSelect<true>;
    'playbook-entries': PlaybookEntriesSelect<false> | PlaybookEntriesSelect<true>;
    'counterparty-drafts': CounterpartyDraftsSelect<false> | CounterpartyDraftsSelect<true>;
    'negotiation-log-entries': NegotiationLogEntriesSelect<false> | NegotiationLogEntriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clause-families".
 */
export interface ClauseFamily {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sub-clauses".
 */
export interface SubClause {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playbook-entries".
 */
export interface PlaybookEntry {
  id: number;
  clauseFamily: number | ClauseFamily;
  subClause: number | SubClause;
  tier: 'ideal' | 'acceptable' | 'fallback_1' | 'fallback_2' | 'walk_away';
  approvalLevelRequired: 'self' | 'senior_counsel' | 'gc' | 'cfo' | 'ceo';
  version: number;
  positionDescription: string;
  rationale?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "counterparty-drafts".
 */
export interface CounterpartyDraft {
  id: number;
  industry: 'saas' | 'finserv' | 'health' | 'retail' | 'public' | 'other';
  counterpartyType: 'customer' | 'vendor' | 'partner';
  counterpartySize: 'smb' | 'mid' | 'ent';
  dealValueBand: 'lt_50k' | '50k_250k' | '250k_1m' | 'gt_1m';
  termLength: 'lt_1y' | '1y' | '2_3y' | 'gt_3y';
  urgency: 'low' | 'medium' | 'high';
  clauseFamily: number | ClauseFamily;
  subClause: number | SubClause;
  clauseText: string;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "negotiation-log-entries".
 */
export interface NegotiationLogEntry {
  id: number;
  counterpartyDraft: number | CounterpartyDraft;
  /**
   * Leave blank if the negotiation was out of playbook (novel position).
   */
  playbookEntry?: (number | null) | PlaybookEntry;
  finalPosition: string;
  approvalLevelUsed: 'self' | 'senior_counsel' | 'gc' | 'cfo' | 'ceo';
  dateClosed: string;
  /**
   * What did we give up in exchange for landing here?
   */
  whatWasTraded?: string | null;
  /**
   * Why the counterparty had (or didn't have) the power to push this position.
   */
  leverage: string;
  /**
   * How material the residual risk is in this deal.
   */
  riskAssessment: string;
  /**
   * What was exchanged or the commercial context driving the decision.
   */
  tradeOrContext: string;
  /**
   * How this affects precedent across future deals.
   */
  precedentManagement: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'clause-families';
        value: number | ClauseFamily;
      } | null)
    | ({
        relationTo: 'sub-clauses';
        value: number | SubClause;
      } | null)
    | ({
        relationTo: 'playbook-entries';
        value: number | PlaybookEntry;
      } | null)
    | ({
        relationTo: 'counterparty-drafts';
        value: number | CounterpartyDraft;
      } | null)
    | ({
        relationTo: 'negotiation-log-entries';
        value: number | NegotiationLogEntry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clause-families_select".
 */
export interface ClauseFamiliesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sub-clauses_select".
 */
export interface SubClausesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playbook-entries_select".
 */
export interface PlaybookEntriesSelect<T extends boolean = true> {
  clauseFamily?: T;
  subClause?: T;
  tier?: T;
  approvalLevelRequired?: T;
  version?: T;
  positionDescription?: T;
  rationale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "counterparty-drafts_select".
 */
export interface CounterpartyDraftsSelect<T extends boolean = true> {
  industry?: T;
  counterpartyType?: T;
  counterpartySize?: T;
  dealValueBand?: T;
  termLength?: T;
  urgency?: T;
  clauseFamily?: T;
  subClause?: T;
  clauseText?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "negotiation-log-entries_select".
 */
export interface NegotiationLogEntriesSelect<T extends boolean = true> {
  counterpartyDraft?: T;
  playbookEntry?: T;
  finalPosition?: T;
  approvalLevelUsed?: T;
  dateClosed?: T;
  whatWasTraded?: T;
  leverage?: T;
  riskAssessment?: T;
  tradeOrContext?: T;
  precedentManagement?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}