# Generated by Django 5.1.15 on 2026-05-15 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClauseFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "verbose_name_plural": "Clause families",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubClause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CounterpartyDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("saas", "SaaS"),
                            ("finserv", "Financial services"),
                            ("health", "Healthcare"),
                            ("retail", "Retail / e-commerce"),
                            ("public", "Public sector"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "counterparty_size",
                    models.CharField(
                        choices=[
                            ("smb", "SMB"),
                            ("mid", "Mid-market"),
                            ("ent", "Enterprise"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "deal_value_band",
                    models.CharField(
                        choices=[
                            ("lt_50k", "< $50k"),
                            ("50k_250k", "$50k – $250k"),
                            ("250k_1m", "$250k – $1M"),
                            ("gt_1m", "> $1M"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "term_length",
                    models.CharField(
                        choices=[
                            ("lt_1y", "< 1 year"),
                            ("1y", "1 year"),
                            ("2_3y", "2–3 years"),
                            ("gt_3y", "3+ years"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "counterparty_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("vendor", "Vendor"),
                            ("partner", "Partner"),
                        ],
                        max_length=20,
                    ),
                ),
                ("clause_text", models.TextField()),
                ("source", models.CharField(default="synthetic", max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clause_family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="playbook.clausefamily",
                    ),
                ),
                (
                    "sub_clause",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="playbook.subclause",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlaybookEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("ideal", "Ideal"),
                            ("acceptable", "Acceptable"),
                            ("fallback_1", "Fallback 1"),
                            ("fallback_2", "Fallback 2"),
                            ("walk_away", "Walk-away"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position_description", models.TextField()),
                (
                    "approval_level_required",
                    models.CharField(
                        choices=[
                            ("self", "Self"),
                            ("senior_counsel", "Senior counsel"),
                            ("gc", "GC"),
                            ("cfo", "CFO"),
                            ("ceo", "CEO"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clause_family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="playbook.clausefamily",
                    ),
                ),
                (
                    "sub_clause",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="playbook.subclause",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Playbook entries",
                "ordering": ["clause_family__name", "sub_clause__name", "tier"],
            },
        ),
        migrations.CreateModel(
            name="NegotiationLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("final_position", models.TextField()),
                (
                    "leverage",
                    models.TextField(
                        help_text="Why the counterparty had (or didn't have) the power to push this position.",
                        verbose_name="Counterparty leverage",
                    ),
                ),
                (
                    "risk_assessment",
                    models.TextField(
                        help_text="How material the residual risk is in this deal."
                    ),
                ),
                (
                    "trade_or_context",
                    models.TextField(
                        help_text="What was exchanged or the commercial context driving the decision.",
                        verbose_name="Trade or context",
                    ),
                ),
                (
                    "precedent_management",
                    models.TextField(
                        help_text="How this affects precedent across future deals."
                    ),
                ),
                (
                    "approval_level_used",
                    models.CharField(
                        choices=[
                            ("self", "Self"),
                            ("senior_counsel", "Senior counsel"),
                            ("gc", "GC"),
                            ("cfo", "CFO"),
                            ("ceo", "CEO"),
                        ],
                        max_length=20,
                    ),
                ),
                ("what_was_traded", models.TextField(blank=True)),
                ("date_closed", models.DateField()),
                (
                    "counterparty_draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="playbook.counterpartydraft",
                    ),
                ),
                (
                    "playbook_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank if the negotiation was out of playbook (novel position).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="playbook.playbookentry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Negotiation log entries",
                "ordering": ["-date_closed"],
            },
        ),
    ]
